# -*- coding: utf-8 -*-
"""lab-ch02-diagnostic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14GA-vvsyich8spF4dhPubL5QkJEz1esq

# Lab 2: Measurement & Indexes — Diagnostic Lab

**ECON 5200: Causal Machine Learning & Applied Analytics**

This lab uses a **diagnosis-first** format. You will:
1. Find and fix 4 bugs in a broken deflation pipeline
2. Compare CPI-U vs. Chained CPI (C-CPI-U) to quantify substitution bias
3. Build a multi-metric KPI dashboard demonstrating Goodhart's Law
4. Write a verification module (`deflation_utils.py`)

**Time estimate:** 45-60 minutes (20 minutes if you already know FRED and pandas well)

**Prerequisites:** Chapter 2 reading, including [5200-DEPTH] sections on index number theory and KPI taxonomy

**AI in the manual parts:** you may ask Colab to *explain* an error or a line of code (click **Explain error**, or select a line and ask Gemini to explain it). Do not ask it to write or fix code, and turn off AI code completion while you work on those parts. AI-assisted coding is allowed only where this lab says so.

## Setup
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


def load_fred(series_id, observation_start="1947-01-01"):
    """Return one FRED series as a pandas Series indexed by date.

    Uses FRED's public CSV endpoint, which needs NO API key and no account.
    Every graded part of this lab runs through this function, so nothing here
    is blocked on a credential.

    FRED has renamed the value column before now, so we set both column names
    positionally rather than trusting the header.
    """
    url = (f"https://fred.stlouisfed.org/graph/fredgraph.csv?"
           f"id={series_id}&cosd={observation_start}")
    frame = pd.read_csv(url)
    frame.columns = ["date", series_id]
    frame["date"] = pd.to_datetime(frame["date"])
    frame[series_id] = pd.to_numeric(frame[series_id], errors="coerce")
    return frame.set_index("date")[series_id].dropna()


# OPTIONAL — the fredapi package does the same job behind a free API key, and
# adds search, metadata and vintages. Nothing in this lab needs it.
#
# If you do want it, the key goes in Colab's secret store, never in this file:
#   left sidebar -> key icon (Secrets) -> + Add new secret
#   Name: FRED_API_KEY    Value: your 32-character key    Notebook access: ON
# Get a free key at https://fredaccount.stlouisfed.org/apikeys.
#
#     !pip install fredapi -q
#     from google.colab import userdata
#     from fredapi import Fred
#     fred = Fred(api_key=userdata.get("FRED_API_KEY"))
#     fred.get_series("CPIAUCSL", observation_start="1964-01-01")
#
# Written this way the key is never in the notebook, so there is nothing to
# strip before you push. Never type a key into a cell, never paste one into an
# AI chat, and never leave one on screen -- a screen share or a recording
# captures it. If that happens, revoke and reissue at the link above.

print("Setup complete! (no API key needed)")

"""<!-- 5200-onramp -->
## Part 0: Build It First (GUIDED — 15 min)

Part 4 of this lab asks you to write `deflation_utils.py` — a **module**, a
file of your own that other code can import. That is the professional
deliverable, and it is a real step up from writing cells. This part builds you
up to it.

**This lab's slice of the floor:** functions — `def`, parameters, default
arguments, docstrings, `return`, and raising an error deliberately — plus the
two ways a notebook turns a cell into an importable `.py` file.

*(If you have not done Lab 1's Part 0, do it first: it covers f-strings, the
DataFrame, and boolean masks, all of which are assumed here.)*
"""

# -----------------------------------------------------------
# GUIDED — Run as-is
# Step 0a: writing a function
# -----------------------------------------------------------
import pandas as pd
import numpy as np

# A FUNCTION is a named, reusable block. `def` starts it, the indented lines
# are its body, and `return` hands a value back to whoever called it.

def real_rate(nominal, inflation_pct):
    """Return the approximate real interest rate (the Fisher approximation).

    Parameters
    ----------
    nominal : float
        Nominal rate, in percent (5.0 means 5%).
    inflation_pct : float
        Inflation rate, in percent.

    Returns
    -------
    float
    """
    return nominal - inflation_pct

print(f"US:     {real_rate(5.25, 3.10):.2f}%")
print(f"Brazil: {real_rate(10.75, 4.50):.2f}%")

# The triple-quoted string is a DOCSTRING -- documentation, not a comment.
# help() prints it, graders read it, and every function in the modules you
# write this term needs one.
help(real_rate)

# DEFAULT ARGUMENTS make a parameter optional.
def compound(start, rate=0.02, years=5):
    """Compound `start` at `rate` for `years`. Rate and years are optional."""
    return start * (1 + rate) ** years

print(f"\nDefaults:            {compound(100):.2f}")
print(f"Override the rate:   {compound(100, rate=0.05):.2f}")
print(f"Override both:       {compound(100, 0.05, 10):.2f}")

# A function with NO return hands back None. That is a real value, and
# "AttributeError: 'NoneType' object has no attribute ..." almost always means
# you used the result of a function that forgot to return anything.
def just_prints(x):
    print(f"  (printed {x}, returned nothing)")

print("\nWhat did just_prints give back?", just_prints(3))

# -----------------------------------------------------------
# GUIDED — Run as-is
# Step 0b: BUILD IT — a correct deflate(), and a deliberate error
# -----------------------------------------------------------
# This is the function Part 1 will show you with a bug in it, and the one you
# will ship as a module in Part 4. Build the correct version now.
#
#     Real value = (Nominal / CPI) * CPI in the base year
#
# Both halves must be in the SAME units and aligned on the SAME dates. The
# classic error is mixing an annual average with a monthly reading, or
# dividing by the base CPI instead of multiplying by it.

# A small CPI series, so this part needs no API key.
demo_dates = pd.date_range("2018-01-01", periods=84, freq="MS")
demo_cpi = pd.Series(100 * (1.0025 ** np.arange(84)), index=demo_dates, name="cpi")
demo_nominal = pd.Series(20 + 0.05 * np.arange(84), index=demo_dates, name="wage")


def deflate(nominal, cpi, base_year=2020):
    """Convert a nominal series to constant base_year dollars.

    `nominal` and `cpi` are PARAMETERS -- names that exist only inside this
    function. That is why they can be short and generic here while the series
    outside are called demo_nominal and demo_cpi.

    Raising on a missing base year is deliberate: returning all-NaN instead
    would let a silent unit error travel downstream into a published number.
    """
    base = cpi.loc[cpi.index.year == base_year]
    if len(base) == 0:
        raise ValueError(f"base_year {base_year} not present in the CPI index")
    return (nominal / cpi) * base.mean()


demo_real = deflate(demo_nominal, demo_cpi, base_year=2020)
print(f"base CPI (2020 mean): {demo_cpi[demo_cpi.index.year == 2020].mean():.2f}")
print(f"first {demo_dates[0].date()}: nominal ${demo_nominal.iloc[0]:.2f} -> real ${demo_real.iloc[0]:.2f}")
print(f"last  {demo_dates[-1].date()}: nominal ${demo_nominal.iloc[-1]:.2f} -> real ${demo_real.iloc[-1]:.2f}")
print(f"\nnominal growth: {(demo_nominal.iloc[-1] / demo_nominal.iloc[0] - 1):.1%}")
print(f"real growth:    {(demo_real.iloc[-1] / demo_real.iloc[0] - 1):.1%}")

# The guard clause, doing its job.
try:
    deflate(demo_nominal, demo_cpi, base_year=1970)
except ValueError as e:
    print(f"\ndeflate(..., base_year=1970) -> ValueError: {e}")

"""### How a notebook makes a real file

Part 4 asks for `deflation_utils.py`. There are two routes and this course uses
both, so recognise each:

**Route 1 — a string, then write it.** What Part 4 of *this* lab does:

```python
module_code = '''
'''Deflation utilities.'''
import pandas as pd

def deflate_series(nominal, cpi, base_year=2020):
    ...
'''
with open("deflation_utils.py", "w") as f:
    f.write(module_code.strip())
```

**Route 2 — the `%%writefile` magic.** What Labs 3, 4 and 5 do. A cell whose
*first line* is `%%writefile eda_utils.py` writes the rest of that cell to disk
instead of running it.

Either way the next cell can `import deflation_utils` like any other library.
Two consequences worth knowing before you hit them:

- The file gets **only what is in that cell**. Imports the functions need must
  be written inside it — the notebook's earlier `import pandas as pd` does not
  travel into the file.
- Python caches imported modules. Writing the file again after an edit does not
  change the already-imported version; you need `importlib.reload(module)`, or
  *Restart session*. That is why Part 4 calls `importlib.reload` right after
  the import.

### Now diagnose

You have a correct `deflate()` and its output on screen. Part 1's version
computes something subtly different. Run it, compare the *numbers* against
what you just produced, and only then go looking for the line.

---

## Part 1: Find and Fix the Bugs (DIAGNOSTIC — 15 min)

The following code attempts to deflate nominal wages using CPI data from FRED. It contains **4 bugs** — common errors that even experienced analysts make. Your job: find each bug, explain why it's wrong, and fix it.

**Hint:** The bugs are related to:
- Base period selection
- Date alignment between the two series
- Missing data handling
- The units the output is actually in

Compare the output against the `deflate()` you built in Step 0b before you
read the function line by line.
"""

# -----------------------------------------------------------
# BROKEN CODE — Find and fix the 4 bugs
# -----------------------------------------------------------

def deflate_series_broken(nominal, cpi, base_year=2020):
    """
    Convert nominal series to real values. Contains 4 bugs.
    """
    base_cpi = cpi.loc[f"{base_year}-01-01"]

    real = (nominal / cpi) * base_cpi

    real = nominal / cpi * 100

    return real

# Pull data
wages = load_fred("AHETPI", observation_start="1964-01-01")
cpi_data = load_fred("CPIAUCSL", observation_start="1964-01-01")

result = deflate_series_broken(wages, cpi_data, base_year=2020)

print(f"Result range: {result.min():.2f} to {result.max():.2f}")
print(f"Rows returned: {len(result)}   of which NaN: {result.isna().sum()}")
print(f"Wage months: {len(wages)}   CPI months: {len(cpi_data)}")
print("\n(If these numbers look wrong, you've identified a bug!)")

"""### Your Fixes

For each bug, explain:
1. **What's wrong** (1 sentence)
2. **Why it matters** (what does the error do to the output?)
3. **The fix** (show the corrected code)

Bug 1:

1. The original code used cpi.loc["2020-01-01"], which is only January 2020. It ignores the other 11 months of the base year.

2. "2020 dollars" means scaling everything by the average CPI across all of 2020, which is what the deflate() in Part 0 does. Using only January 2020 gives a base that's usually lower than the year's true average, since prices tend to rise through the year. That makes every real value the wrong size by the same proportion. The overall shape and growth rates stay the same, but the dollar levels are off, and they no longer match the checkpoint numbers.

3. Fix: base_cpi = cpi.loc[cpi.index.year == base_year].mean()

Bug 2:

1. Dividing nominal / cpi lines the two series up on the dates from both of them. If a date is in only one series, pandas keeps it anyway and puts a NaN in the result.

2. The result ends up with rows where one input had no data, so it isn't limited to the dates where both series are observed. That inflates the row count and breaks the checks that come after.

3. Find the dates both series share with nominal.index.intersection(cpi.index), then select those dates from each series before dividing. That way the division only uses matched pairs.

Bug 3:

1. The function can return NaN values in its result instead of removing them, so the output isn't guaranteed to be free of missing data.

2. NaNs behave differently depending on what touches them next. A .mean() skips them, but arithmetic passes them along, and a plot leaves gaps. Nothing at the call site tells you it happened, so the problem stays hidden until a number looks wrong later.

3. Fix: Add .dropna() before returning. Because the inputs here were already cleaned when loaded, it's a safeguard that makes the "no missing values" promise hold regardless of what's passed in.

Bug 4:

1. The line real = nominal / cpi * 100 runs after the correct calculation and overwrites it. It drops the base_cpi multiplication, and it ignores base_year entirely, because the 100 is hard-coded.

2. Dividing by CPI and multiplying by 100 puts wages in 1982-84 dollars, which is the CPI's own reference period, but the docstring and code claim they're in base_year dollars. The numbers look like plausible wages, so the wrong-year label is easy to miss. That's why the broken output was 7.62 to 9.82 instead of about 19.71 to 25.42.

3. Delete the overwriting line so the correct (nominal / cpi) * base_cpi result is the one returned.
"""

# -----------------------------------------------------------
# ✏️ YOUR TASK — Write the corrected function
# -----------------------------------------------------------

def deflate_series_fixed(nominal, cpi, base_year=2020):
    """Convert a nominal time series to constant base_year dollars.

    Returns a Series with no missing values, indexed by the dates on which
    BOTH inputs are observed.
    """
    base = cpi.loc[cpi.index.year == base_year]
    if len(base) == 0:
        raise ValueError(f"base_year {base_year} not present in the CPI index")
    base_cpi = base.mean()

    common_dates = nominal.index.intersection(cpi.index)
    real = (nominal.loc[common_dates] / cpi.loc[common_dates]) * base_cpi
    return real.dropna()


wages_real = deflate_series_fixed(wages, cpi_data, base_year=2020)
if wages_real is None:
    raise NotImplementedError("deflate_series_fixed still returns None -- write its body above.")

print(f"Real wage range: ${wages_real.min():.2f} to ${wages_real.max():.2f} (2020 $)")
print(f"Real wage in Jan 1973: ${wages_real.loc['1973-01-01']:.2f}")
print(f"Real wage latest ({wages_real.index[-1]:%b %Y}): ${wages_real.iloc[-1]:.2f}")

"""### Verification Checkpoint

Measured against live FRED (FRED revises, so the second decimal can move):

| | 2020 dollars |
|---|---|
| Jan 1973 | **\$24.43** |
| Latest month | about **\$25.20** |
| Series minimum | \$19.71 (1995) |
| Series maximum | **\$25.42, April 2020** — a composition effect, not a raise |

Before 2000 the peak is January 1973; the all-time maximum is April 2020.

The broken function's 7.62 to 9.82 is not "index units". Dividing by the CPI
and multiplying by 100 expresses wages in **1982–84 dollars**, the CPI's own
reference period, while the code claims 2020 dollars. The number is a real
wage; it is labelled with the wrong year.

Then run the check below. It tests the arithmetic rather than a hard-coded
number, so it keeps working as FRED revises.
"""

# -----------------------------------------------------------
# CHECK — Run as-is after your fix
# -----------------------------------------------------------

def check_deflated(real, nominal, cpi, base_year):
    """Raise AssertionError unless `real` is `nominal` in base_year dollars."""
    assert real is not None, "Got None: the function has no return statement yet."
    n_nan = int(real.isna().sum())
    assert n_nan == 0, f"{n_nan} NaN row(s) in the result."
    rows = real.index.intersection(nominal.index).intersection(cpi.index)
    assert len(rows) == len(real), (
        f"{len(real) - len(rows)} row(s) fall on dates missing from the wage or CPI series.")
    implied_base = real[rows] / nominal[rows] * cpi[rows]
    target = cpi[cpi.index.year == base_year].mean()
    assert np.allclose(implied_base, target, rtol=1e-6), (
        f"The result is scaled to a CPI of {implied_base.median():.2f}; "
        f"base_year={base_year} requires {target:.2f}.")
    return True


check_deflated(wages_real, wages, cpi_data, base_year=2020)
check_deflated(deflate_series_fixed(wages, cpi_data, base_year=2017),
               wages, cpi_data, base_year=2017)
print("Part 1 checks passed: no NaN, aligned dates, and the base_year argument is honoured.")

"""## Part 2: CPI-U vs. Chained CPI — Quantifying Substitution Bias (EXTEND — 15 min)

The chapter discussed how the Laspeyres CPI overstates inflation due to substitution bias. The BLS publishes the Chained CPI (C-CPI-U, FRED series SUUR0000SA0) as a partial correction. Let's quantify the gap.

**Compare like with like.** C-CPI-U is published **not seasonally adjusted**,
with **December 1999 = 100**. The CPI-U you used in Part 1 (`CPIAUCSL`) is
seasonally adjusted, so this part pulls the unadjusted CPI-U, `CPIAUCNS`, from
the same month. Mixing the two makes the end-point gap swing by more than a
full index point depending on which month the data happens to end in.

One more property of the series: the last 10–12 months of C-CPI-U are
**preliminary** and are revised as expenditure data arrive, so the most recent
decimal of any gap you compute is provisional.
"""

# -----------------------------------------------------------
# Pull both CPI variants, not seasonally adjusted, from Dec 1999
# -----------------------------------------------------------
cpi_u = load_fred("CPIAUCNS", observation_start="1999-12-01")
cpi_u.name = "CPI-U"

# C-CPI-U (Chained CPI) — FRED series SUUR0000SA0
try:
    cpi_c = load_fred("SUUR0000SA0", observation_start="1999-12-01")
    cpi_c.name = "C-CPI-U"
    print(f"CPI-U observations: {len(cpi_u)}")
    print(f"C-CPI-U observations: {len(cpi_c)}")
except Exception as e:
    print(f"C-CPI-U not available: {e}")
    print("Using synthetic approximation instead.")
    # Approximate: C-CPI-U compounds about 0.27 pp/year slower than CPI-U
    cpi_c = cpi_u / 1.0027 ** (np.arange(len(cpi_u)) / 12)
    cpi_c.name = "C-CPI-U (approx)"

combined = pd.DataFrame({"CPI-U": cpi_u, "C-CPI-U": cpi_c}).dropna()
combined_norm = combined / combined.iloc[0] * 100

fig, ax = plt.subplots(figsize=(10, 5))
ax.plot(combined_norm.index, combined_norm["CPI-U"],
        label="CPI-U (standard, NSA)", color="#D32F2F", linewidth=2)
ax.plot(combined_norm.index, combined_norm["C-CPI-U"],
        label="C-CPI-U (chained)", color="#1976D2", linewidth=2)
ax.set_xlabel("Year")
ax.set_ylabel("Index (Dec 1999 = 100)")
ax.set_title("CPI-U vs. Chained CPI: Measuring Substitution Bias")
ax.legend(frameon=False)
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)
plt.tight_layout()
plt.show()

years = (combined_norm.index[-1] - combined_norm.index[0]).days / 365.25
gap_points = combined_norm["CPI-U"].iloc[-1] - combined_norm["C-CPI-U"].iloc[-1]
print(f"Cumulative gap over {years:.1f} years: {gap_points:.1f} index points")
print(f"That is {gap_points / years:.2f} index points per year.")

# YOUR TASK: the Boskin Commission, the BLS and the chapter all state
# substitution bias in PERCENTAGE POINTS OF INFLATION PER YEAR. Index points
# per year is not that quantity. Compute the average annual inflation rate of
# each index over `years`, in percent, and take the difference.
cpi_u_rate = 100 * ((combined_norm["CPI-U"].iloc[-1] / combined_norm["CPI-U"].iloc[0]) ** (1 / years) - 1) # CPI-U average annual inflation, percent per year
cpi_c_rate = 100 * ((combined_norm["C-CPI-U"].iloc[-1] / combined_norm["C-CPI-U"].iloc[0]) ** (1 / years) - 1)         # C-CPI-U average annual inflation, percent per year
annual_gap_pp = cpi_u_rate - cpi_c_rate


print(f"\nCPI-U:   {cpi_u_rate:.2f}% per year")
print(f"C-CPI-U: {cpi_c_rate:.2f}% per year")
print(f"Upper-level substitution bias: {annual_gap_pp:.2f} pp per year")

# -----------------------------------------------------------
# CHECK — Run as-is
# -----------------------------------------------------------
for label, rate in [("CPI-U", cpi_u_rate), ("C-CPI-U", cpi_c_rate)]:
    end = combined_norm[label].iloc[-1]
    # Accept either convention: annual compounding or a continuous (log) rate.
    annual = 100 * (1 + rate / 100) ** years
    continuous = 100 * np.exp(rate / 100 * years)
    assert min(abs(annual - end), abs(continuous - end)) < 0.5, (
        f"{label}: {rate:.3f}% a year for {years:.1f} years does not take the "
        f"index from 100 to {end:.1f}. Check the units: percent, per year.")
print(f"Part 2 check passed: {annual_gap_pp:.2f} pp per year.")

"""### Interpretation Question

**Q1:** The Boskin Commission (1996) put total substitution bias at about
0.4 pp per year: **0.15 pp upper-level** (substitution *between* item
categories) and **0.25 pp lower-level** (substitution *within* a category).
Since January 1999 the CPI-U itself uses a geometric mean for most lower-level
indexes. Which of Boskin's two components does your CPI-U vs C-CPI-U gap
measure, and is your estimate above or below Boskin's figure for it? Give one
reason the 2000–present number might differ from a 1996 estimate.

**Q2:** Your print-out above shows both index points per year and percentage
points per year. Explain in two sentences why they differ, and which one a
cost-of-living adjustment compounds.

**Q3:** Social Security COLAs are indexed to CPI-W, a close relative of CPI-U.
Treat the two as equal, and use your pp-per-year estimate: by roughly what
percentage would a benefit be lower after a 20-year retirement if COLAs
followed C-CPI-U instead? Federal tax brackets have been indexed to C-CPI-U
since 2017 — who gains and who loses from that switch?

*Your answers here:*

Q1: The gap between CPI-U and C-CPI-U measures the upper-level substitution bias, which is substitution between categories. Since 1999, CPI-U has used the same geometric-mean formula as C-CPI-U within categories, so the lower-level part is already handled. The only remaining difference is that C-CPI-U lets the spending weights shift across categories. My estimate is 0.27 pp per year, which is above Boskin's 0.15. One possible reason is that my sample includes the 2021-23 inflation surge, when prices of things like energy, food, and services moved far apart, and that's when substitution matters most. Boskin's estimate came from a calmer period.

Q2. Index points per year depends on the level of the index, because one point means less as the index grows: 1 point on 100 is 1%, but 1 point on 250 is 0.4%. So it isn't a true rate. Percentage points per year is a rate, so it stays comparable across time. A COLA applies a percentage increase to a benefit every year, so it's the pp per year figure that compounds.

Q3. Using my rates of 2.61% for CPI-U and 2.35% for C-CPI-U, a benefit indexed to C-CPI-U would be 1 − (1.0235/1.0261)^20, which is about 4.95%, or roughly 5% lower after 20 years. On the tax side, brackets indexed to C-CPI-U rise more slowly, so over time more income falls into higher brackets. Taxpayers lose because their taxes rise faster than they would under CPI-U, and the government gains from the extra revenue.

## Part 3: KPI Dashboard — Detecting Goodhart's Law (BUILD — 15 min)

Build a dashboard that monitors a primary metric AND a counter-metric to detect when gaming occurs. We'll simulate an engagement metric (like DAU/MAU) with synthetic data.
"""

# -----------------------------------------------------------
# Simulate a Goodhart scenario: DAU/MAU rises while quality falls
# -----------------------------------------------------------
np.random.seed(42)
n_months = 36  # 3 years
dates = pd.date_range("2022-01-01", periods=n_months, freq="MS")

# Phase 1 (months 0-17): Organic growth — both metrics improve
# Phase 2 (months 18-35): Gaming — notification spam inflates DAU/MAU
#                          but quality (time per session) declines

dau_mau = np.concatenate([
    0.45 + 0.005 * np.arange(18) + np.random.normal(0, 0.01, 18),  # organic
    0.54 + 0.008 * np.arange(18) + np.random.normal(0, 0.01, 18),  # gaming
])

time_per_session = np.concatenate([
    8.0 + 0.15 * np.arange(18) + np.random.normal(0, 0.3, 18),     # organic
    10.7 - 0.2 * np.arange(18) + np.random.normal(0, 0.3, 18),     # declining
])

kpi_data = pd.DataFrame({
    "DAU/MAU": dau_mau,
    "Time per Session (min)": time_per_session
}, index=dates)

print(kpi_data.describe().round(2))

# -----------------------------------------------------------
# GUIDED — the dashboard
# Left panel: DAU/MAU over time (primary metric)
# Right panel: Time per session over time (counter-metric)
# The vertical line marks month 18, when gaming began
# -----------------------------------------------------------

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

# Primary metric
ax1.plot(kpi_data.index, kpi_data["DAU/MAU"], color="#2196F3",
         linewidth=2, marker="o", markersize=3)
ax1.axvline(x=dates[18], color="red", linestyle="--", alpha=0.5,
            label="Gaming begins")
ax1.set_title("Primary Metric: DAU/MAU", fontsize=13)
ax1.set_ylabel("DAU/MAU Ratio")
ax1.legend(frameon=False)
ax1.spines["top"].set_visible(False)
ax1.spines["right"].set_visible(False)

# Counter-metric
ax2.plot(kpi_data.index, kpi_data["Time per Session (min)"],
         color="#FF9800", linewidth=2, marker="s", markersize=3)
ax2.axvline(x=dates[18], color="red", linestyle="--", alpha=0.5,
            label="Gaming begins")
ax2.set_title("Counter-Metric: Time per Session", fontsize=13)
ax2.set_ylabel("Minutes")
ax2.legend(frameon=False)
ax2.spines["top"].set_visible(False)
ax2.spines["right"].set_visible(False)

plt.suptitle("Detecting Goodhart's Law: When Metrics Diverge", fontsize=15, y=1.02)
plt.tight_layout()
plt.show()

# -----------------------------------------------------------
# ✏️ YOUR TASK — Measure the divergence
# Two blanks. The chart shows it; a monitoring system needs a number.
# -----------------------------------------------------------

# Correlation between DAU/MAU and time per session, within each phase.
# Months 0-17 are the organic phase; months 18-35 are the gaming phase.
corr_organic = kpi_data["DAU/MAU"].iloc[:18].corr(kpi_data["Time per Session (min)"].iloc[:18])
corr_gaming = kpi_data["DAU/MAU"].iloc[18:].corr(kpi_data["Time per Session (min)"].iloc[18:])

print(f"Correlation (organic phase): {corr_organic:+.2f}")
print(f"Correlation (gaming phase):  {corr_gaming:+.2f}")
if corr_organic > 0 and corr_gaming < 0:
    print("\nSign flip = Goodhart's Law detected!")

"""### Interpretation Question

**Q1:** In the organic phase, DAU/MAU and time-per-session are positively correlated. In the gaming phase, they become negatively correlated. Explain why this sign flip is a diagnostic signal for Goodhart's Law.

**Q2:** You are a product economist at this company. The VP of Growth shows the DAU/MAU chart (left panel only) and says, "Engagement is up 30% — great quarter!" What would you say?

*Your answers here:*

Q1: In the organic phase, DAU/MAU and time per session rise together because they share a cause: a better product brings people back more often and keeps them engaged once they're there. Once DAU/MAU becomes the target and the company starts pushing notifications, that link breaks. The visits it produces are low-intent, so DAU/MAU goes up while session quality goes down. The sign flip is a warning because "more of the same good thing" wouldn't reverse the relationship. It happens when the metric and the goal it was meant to represent get pulled apart, which is what Goodhart's Law describes.

Q2: I'd say the 30% increase is real, but it doesn't tell us the quarter went well. DAU/MAU went up while time per session went down, and until now those two moved together. That pattern looks like gaming rather than real improvement. Before calling it a great quarter, I'd want to see time per session next to it, and I'd suggest we never report DAU/MAU by itself again.

## Part 4: Write a Verification Module (PRODUCTION — 10 min)

Save your fixed `deflate_series()` function as a standalone Python module that can be imported in future labs.

Copy the **body** of your `deflate_series_fixed` from Part 1 into the module
below, keeping the docstring and the guard clauses that are already there.

**Also carry Lab 1 forward.** Paste the `profile_dataframe()` you wrote in
Lab 1 Part 3 into the same file, so `deflation_utils.py` holds both. It is the
function you will reach for first on every new dataset this term, and a module
you can `import` is a portfolio artifact in a way a notebook cell is not.
Give it the same docstring treatment as `deflate_series()`.

The verification at the bottom reuses Part 1's `check_deflated`, so the module
is tested against the definition of a base-year deflation, not against your own
earlier output.
"""

# -----------------------------------------------------------
# ✏️ YOUR TASK — Write deflation_utils.py
# -----------------------------------------------------------
module_code = '''
"""Deflation utilities for ECON 5200 labs."""

import pandas as pd


def deflate_series(nominal, cpi, base_year=2020):
    """Convert a nominal time series to real (constant-dollar) values.

    Parameters
    ----------
    nominal : pd.Series
        Nominal values indexed by date.
    cpi : pd.Series
        CPI values indexed by date, at the SAME frequency and with the SAME
        seasonal adjustment as `nominal`.
    base_year : int
        Year whose dollars to express values in. The base is that year's
        average CPI.

    Returns
    -------
    pd.Series
        Real values in base_year dollars, on the dates both inputs share,
        with no missing values.

    Raises
    ------
    ValueError
        If base_year is not present in the CPI index, or if the two series
        share no dates.
    """
    if not (cpi.index.year == base_year).any():
        raise ValueError(f"Base year {base_year} not found in CPI data.")

    base_cpi = cpi.loc[cpi.index.year == base_year].mean()

    common_dates = nominal.index.intersection(cpi.index)
    if len(common_dates) == 0:
        raise ValueError("nominal and cpi share no common dates.")

    real = (nominal.loc[common_dates] / cpi.loc[common_dates]) * base_cpi
    return real.dropna()


def profile_dataframe(data, unit_col="name", time_col="date"):
    """Return a dict describing the structure and completeness of `data`.

    Parameters
    ----------
    data : pd.DataFrame
        The dataset to profile.
    unit_col : str, default "name"
        Column identifying the cross-sectional unit (e.g. country).
    time_col : str, default "date"
        Column identifying the time period.

    Returns
    -------
    dict
        Keys: shape, n_units, n_periods, structure (one of "panel",
        "time series", "cross-sectional"), complete_units, balanced
        (True if every unit appears in every period), and missing
        (per-column % missing).
    """
    profile = {}
    profile["shape"] = data.shape

    profile["n_units"] = data[unit_col].nunique()
    profile["n_periods"] = data[time_col].nunique()

    if profile["n_units"] > 1 and profile["n_periods"] > 1:
        profile["structure"] = "panel"
    elif profile["n_periods"] > 1:
        profile["structure"] = "time series"
    else:
        profile["structure"] = "cross-sectional"

    periods_per_unit = data.groupby(unit_col)[time_col].size()

    complete = periods_per_unit[periods_per_unit == profile["n_periods"]]
    profile["complete_units"] = len(complete)
    profile["balanced"] = profile["complete_units"] == profile["n_units"]

    missing = {}
    for col in data.columns:
        missing[col] = round(data[col].isna().mean() * 100, 1)
    profile["missing"] = missing

    return profile
'''

with open("deflation_utils.py", "w") as f:
    f.write(module_code.strip())

print("deflation_utils.py saved!")
print("\nVerification test:")

import importlib
import deflation_utils
importlib.reload(deflation_utils)

check_deflated(deflation_utils.deflate_series(wages, cpi_data, base_year=2020),
               wages, cpi_data, base_year=2020)
print("Module passes the Part 1 check.")

"""---
## AI-Assisted Expansion: Index-Integrity Monitor

**The Generative AI Policy: Foundations First, Expansion Second.** You have now established manual mastery over debugging a deflation pipeline, measuring substitution bias in the right units, and detecting a Goodhart sign flip. You are now authorized to operate under the "Co-Pilot Rule."

### Your Expansion Task
Build ONE interactive monitor, inside this notebook (ipywidgets + plotly), that lets the user:
1. Pick a start date and see the CPI-U vs C-CPI-U gap recomputed in **both** index points per year and percentage points per year
2. Switch between the seasonally adjusted and unadjusted CPI-U and see why the gap moves
3. Set a rolling-window length and watch the rolling correlation between DAU/MAU and time per session
4. Get an alert on the first window where that correlation turns negative

Use the functions you already built; do not write a second module.

### P.R.I.M.E. Prompt
Copy and paste this into Claude or ChatGPT:
"""

# -----------------------------------------------------------
# 🤖 AI EXPANSION — Co-Pilot required
# Copy the P.R.I.M.E. prompt above into Claude, then paste
# the generated code here. Run it and verify.
# -----------------------------------------------------------

# [Prep] Act as an expert Python data scientist specializing
# in price-index measurement and KPI monitoring.
#
# [Request] I just completed a diagnosis-first lab where I fixed
# a four-bug deflation function (deflate_series_fixed), measured
# the CPI-U vs C-CPI-U substitution bias as a difference of
# annual inflation rates in percentage points per year, and
# detected a Goodhart sign flip between DAU/MAU and time per
# session. Build ONE interactive monitor that runs in Colab:
#   1. a start-date picker that recomputes the CPI-U vs C-CPI-U
#      gap as index points per year AND as pp per year
#   2. a toggle between CPIAUCNS and CPIAUCSL for CPI-U
#   3. a rolling-window slider for the correlation between the
#      two columns of kpi_data
#   4. an alert naming the first window where it turns negative
#
# [Iterate] Use ipywidgets, plotly and pandas. Reuse my names:
# load_fred, cpi_u, cpi_c, combined_norm, kpi_data,
# deflation_utils.deflate_series. No Streamlit, no new .py file.
#
# [Mechanism Check] Add inline comments explaining:
#   - why index points per year is not a rate, and how the pp
#     figure is computed from compounding
#   - why C-CPI-U must be compared with the unadjusted CPI-U
#   - how the rolling window trades detection speed for noise
#
# [Evaluate] Explain which Boskin component the gap measures,
# and what a monitoring team should do when the alert fires.

# PASTE AI-GENERATED CODE BELOW:

# -----------------------------------------------------------
# AI EXPANSION -- Index-Integrity Monitor (paste into ONE notebook cell)
# Needs, from earlier cells: load_fred, cpi_u (CPIAUCNS), cpi_c, combined_norm,
# kpi_data, annual_gap_pp, and deflation_utils (written in Part 4).
# -----------------------------------------------------------
import importlib
import ipywidgets as widgets
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from IPython.display import display, HTML, clear_output

import deflation_utils
importlib.reload(deflation_utils)

# --- The two CPI-U variants the toggle switches between ------------------
# cpi_u from Part 2 is CPIAUCNS (not seasonally adjusted). Pull CPIAUCSL from
# the same month so both variants cover the same dates as C-CPI-U.
cpi_u_nsa = cpi_u
cpi_u_sa = load_fred("CPIAUCSL", observation_start="1999-12-01")
CPI_CHOICES = {
    "CPIAUCNS (not seasonally adjusted)": cpi_u_nsa,
    "CPIAUCSL (seasonally adjusted)": cpi_u_sa,
}

GAMING_START = kpi_data.index[18]   # known only because Part 3 simulated it


def gap_stats(cpi_u_choice, start_date):
    """Recompute the CPI-U vs C-CPI-U gap from `start_date` to the last month.

    Returns (norm, years, index_pts_per_year, rates, gap_pp), or None if the
    window is shorter than a year (an annual rate is meaningless there).
    """
    # MECHANISM CHECK (why C-CPI-U must be compared with the UNADJUSTED CPI-U):
    # C-CPI-U is published not seasonally adjusted. Pairing it with the
    # seasonally adjusted CPI-U compares two series with different seasonal
    # patterns, so the end-point gap depends on which calendar month the data
    # happens to end in, and a seasonal wiggle gets read as substitution bias.
    combined = pd.DataFrame({"CPI-U": cpi_u_choice, "C-CPI-U": cpi_c}).dropna()
    window = combined.loc[combined.index >= pd.Timestamp(start_date)]
    if len(window) < 13:
        return None

    # Re-base both indexes to 100 at the chosen start month.
    norm = window / window.iloc[0] * 100
    years = (norm.index[-1] - norm.index[0]).days / 365.25
    end = norm.iloc[-1]

    # MECHANISM CHECK (why index points per year is NOT a rate):
    # (end - start) / years assumes growth is a straight line and depends on
    # the index level: one point is 1% at 100 but only 0.4% at 250. Inflation
    # compounds, so the rate is the r that solves
    #     end = start * (1 + r) ** years   ->   r = (end / start) ** (1/years) - 1
    # and the substitution-bias estimate is the difference of those two rates.
    index_pts_per_year = (end["CPI-U"] - end["C-CPI-U"]) / years
    rates = 100 * ((end / 100) ** (1 / years) - 1)
    gap_pp = rates["CPI-U"] - rates["C-CPI-U"]
    return norm, years, index_pts_per_year, rates, gap_pp


def rolling_corr(window):
    """Rolling correlation of the two KPI columns, plus the first negative window."""
    # MECHANISM CHECK (rolling window: speed versus noise):
    # A SHORT window reacts fast after gaming starts but is noisy and can flip
    # sign on random wiggles. A LONG window is stable but still contains
    # organic-phase months after gaming starts, so the alert arrives later.
    r = kpi_data["DAU/MAU"].rolling(window).corr(kpi_data["Time per Session (min)"])
    negative = r[r < 0]
    first = negative.index[0] if len(negative) else None
    return r, first


# --- Controls ------------------------------------------------------------
start_picker = widgets.DatePicker(description="Start date",
                                  value=cpi_c.index[0].date())
cpi_toggle = widgets.ToggleButtons(options=list(CPI_CHOICES),
                                   description="CPI-U series")
window_slider = widgets.IntSlider(value=12, min=4, max=24, step=1,
                                  description="Rolling window (months)",
                                  style={"description_width": "initial"},
                                  continuous_update=False)
controls = widgets.VBox([start_picker, cpi_toggle, window_slider])
output = widgets.Output()


def update(start, cpi_choice, window):
    with output:
        clear_output(wait=True)
        if start is None:
            display(HTML("<b>Pick a start date.</b>"))
            return

        cpi_u_choice = CPI_CHOICES[cpi_choice]
        stats = gap_stats(cpi_u_choice, start)
        if stats is None:
            display(HTML("<b>Window under 12 months.</b> Choose an earlier "
                         "start date so the annual rate means something."))
            return
        norm, years, idx_pts, rates, gap_pp = stats
        r, first_neg = rolling_corr(window)

        # Reuse deflation_utils.deflate_series: what is a flat $1,000 benefit
        # worth at the end of the window, in start-year dollars, under each index?
        base_year = norm.index[0].year
        flat = pd.Series(1000.0, index=norm.index)
        real_u = deflation_utils.deflate_series(flat, cpi_u_choice, base_year).iloc[-1]
        real_c = deflation_utils.deflate_series(flat, cpi_c, base_year).iloc[-1]

        # --- Readout ---
        display(HTML(
            f"<b>Window:</b> {norm.index[0]:%b %Y} to {norm.index[-1]:%b %Y} "
            f"({years:.1f} years)<br>"
            f"<b>CPI-U:</b> {rates['CPI-U']:.2f}%/yr &nbsp; "
            f"<b>C-CPI-U:</b> {rates['C-CPI-U']:.2f}%/yr<br>"
            f"<b>Gap:</b> {gap_pp:.2f} pp per year &nbsp;|&nbsp; "
            f"{idx_pts:.2f} index points per year "
            f"<i>(not a rate; depends on the index level)</i><br>"
            f"<b>A flat $1,000 benefit at window end, in {base_year} dollars:</b> "
            f"${real_u:,.0f} (CPI-U) vs ${real_c:,.0f} (C-CPI-U)"))

        # Tie back to the manual work: at the default Dec 1999 start with the
        # unadjusted CPI-U, this must equal the Part 2 answer.
        if (norm.index[0] == combined_norm.index[0]
                and cpi_choice.startswith("CPIAUCNS")):
            display(HTML(f"<i>Check vs Part 2: {gap_pp:.2f} vs "
                         f"{annual_gap_pp:.2f} pp per year "
                         f"({'match' if abs(gap_pp - annual_gap_pp) < 0.005 else 'MISMATCH'})"
                         f"</i>"))
        if cpi_choice.startswith("CPIAUCSL"):
            display(HTML("<span style='color:#b45309'>Seasonally adjusted CPI-U "
                         "vs unadjusted C-CPI-U: not like with like. Compare "
                         "the gap with the unadjusted setting.</span>"))

        # --- Alert (first window where the rolling correlation is negative) ---
        if first_neg is None:
            display(HTML(f"<b>No alert:</b> the {window}-month rolling "
                         f"correlation never turns negative."))
        else:
            pos = kpi_data.index.get_loc(first_neg)
            win_start = kpi_data.index[pos - window + 1]
            lag = pos - kpi_data.index.get_loc(GAMING_START)
            display(HTML(
                f"<div style='background:#fee2e2;padding:6px;border-radius:4px'>"
                f"<b>ALERT:</b> first negative window is {win_start:%b %Y} to "
                f"{first_neg:%b %Y} (r = {r.loc[first_neg]:+.2f}). "
                f"That is {lag} months after gaming began in "
                f"{GAMING_START:%b %Y}.</div>"))

        # --- Figure ---
        fig = make_subplots(rows=1, cols=2, subplot_titles=(
            f"Indexes re-based to 100 ({norm.index[0]:%b %Y})",
            f"{window}-month rolling correlation"))
        fig.add_trace(go.Scatter(x=norm.index, y=norm["CPI-U"], name="CPI-U",
                                 line=dict(color="#D32F2F")), row=1, col=1)
        fig.add_trace(go.Scatter(x=norm.index, y=norm["C-CPI-U"], name="C-CPI-U",
                                 line=dict(color="#1976D2")), row=1, col=1)
        fig.add_trace(go.Scatter(x=r.index, y=r, name="rolling corr",
                                 line=dict(color="#FF9800")), row=1, col=2)
        fig.add_hline(y=0, line_dash="dot", row=1, col=2)
        for d, colour in [(GAMING_START, "gray"), (first_neg, "red")]:
            if d is not None:
                fig.add_shape(type="line", x0=d, x1=d, y0=0, y1=1,
                              xref="x2", yref="y2 domain",
                              line=dict(color=colour, dash="dash"))
        fig.update_layout(height=420, margin=dict(t=50, b=30),
                          legend=dict(orientation="h", y=-0.15))
        fig.show()


ui = widgets.interactive_output(
    update, {"start": start_picker, "cpi_choice": cpi_toggle, "window": window_slider})
display(controls, output, ui)

# -----------------------------------------------------------
# EVALUATE
# Boskin component: CPI-U has used geometric means for most lower-level indexes
# since Jan 1999, so the CPI-U vs C-CPI-U gap isolates the UPPER-level
# component (substitution between categories). Boskin's figure for it is
# 0.15 pp per year; this monitor's gap should be compared with that, not with
# the 0.4 total.
#
# When the alert fires: treat it as a red flag, not proof. (1) Put the counter-
# metric next to the target metric in every report. (2) Look for what changed
# at the start of the flagged window (notification volume, who the users are).
# (3) Check the window length: a short window may be noise. (4) Do not reward
# the team on the target metric until the divergence is explained.
# -----------------------------------------------------------

"""### Document the interaction

Three short answers. This is what is graded for the expansion, not the code.

1. **What did the AI get wrong or leave out?** Name one line you had to change,
   or one claim in its explanation that your own output contradicts.

2. **How did you verify it?** Point to a number the dashboard shows that you

   also computed by hand earlier in this lab, and say whether they match.
3. **What would you ask differently next time?**

*Your answers here:*

1.
The code ran without errors, so I didn't have to fix a line. What it left out was how strong the alert should be. It fires on the first window where the correlation dips below zero, which in my run was Feb 2023 to Jan 2024 at r = -0.20. That is barely negative, and it came 6 months after gaming began in Jul 2023, whereas the gaming-phase correlation I calculated by hand was -0.96. It also hard-codes the gaming start date to work out that delay, which is only known because the data is simulated, so a real team wouldn't have it.

2.
With the start date at Dec 1999 and the unadjusted CPI-U, the monitor showed CPI-U at 2.61% a year, C-CPI-U at 2.35%, a gap of 0.27 pp per year, and 0.50 index points per year. Those match what I computed by hand in Part 2, and the monitor's own check line printed a match against my Part 2 value.

3.
I'd ask for an alert threshold instead of "first negative," such as a correlation below -0.5 or several negative windows in a row, so one noisy dip doesn't just set it off.

---
## Digital Portfolio: Institutional Signaling

### Generate Your Professional README
Copy and paste the prompt below into Claude or ChatGPT. **Do NOT ask the AI to write Python code — only documentation.** Replace every `[YOUR VALUE]` with the number from your own output before you paste it.
"""

# -----------------------------------------------------------
# 🤖 AI EXPANSION — README generation (no code, just docs)
# -----------------------------------------------------------

# PASTE THIS PROMPT INTO CLAUDE:
#
# "I need help writing a project description for my data science lab.
# **Important Rule:** Do NOT generate any Python code for me.
#
# **What I did in this lab:**
# * Diagnosed and fixed four bugs in a deflation pipeline, including
#   output in 1982-84 dollars mislabelled as 2020 dollars
# * Measured upper-level substitution bias: CPI-U [2.61]% a year vs
#   C-CPI-U [2.35]% a year = [0.27] pp per year, and explained
#   why the [0.50] index-point gap per year is not that number
# * Detected Goodhart's Law as a correlation flip from [+0.93] to
#   [-0.96] between DAU/MAU and time per session
# * Shipped deflation_utils.py with a tested deflate_series()
# * Built an interactive index-integrity monitor
#
# **Please write a README.md entry including:**
# 1. Project Title: Index Integrity — Deflation, Substitution Bias & Goodhart
# 2. Objective: A professional one-sentence summary
# 3. Methodology: Bullet points of technical steps
# 4. Key Findings: Summary of results
# Make this sound like a professional applied econometrician wrote it."

"""---

## Submit this lab on GitHub

**Repository name for this lab:** `econ5200-lab02-deflation`

**First time?** Read the **GitHub Setup and Repository Guide** page in the Start Here module once,
start to finish. It assumes you have never used git and never seen GitHub.

1. On [github.com](https://github.com): **+** (top right) → **New repository**.
   Name it exactly `econ5200-lab02-deflation`, tick **Add a README file**, and create it.
2. In Colab: **File → Save a copy in GitHub**. Choose `econ5200-lab02-deflation`, branch `main`,
   commit message `Lab 02 submission`. This pushes the notebook, and the
   notebook's rendered output — charts included — is what is graded.
3. Open the repo on github.com, click `README.md`, then the pencil icon, and
   paste in the README you drafted from the README prompt above. **Commit
   changes.** Check every number in it against your own output first: this
   goes out under your name.
4. `deflation_utils.py` is **not** pushed by step 2 — that step sends the
   notebook only, and the file lives in Colab's temporary storage, which is
   wiped when the session ends. Download it first: in the Colab **Files** panel
   (folder icon, left), right-click `deflation_utils.py` → **Download**. Then on
   the repo page use **Add file → Upload files**, drag it in, and **Commit
   changes**. It is part of what is graded.
5. On Canvas: in Colab use **File → Download → Download .ipynb**, upload that
   file to the assignment, and paste your repository URL in the **Comments**
   box beside the upload. Then click **Submit**. Do not use the Website URL
   tab: Canvas keeps one submission, so a URL sent on its own replaces your
   notebook.

No terminal, no token, nothing to install.

---

**Lab 2 complete!** You've debugged a deflation pipeline, quantified substitution bias empirically, built a Goodhart detection dashboard, and produced a reusable Python module. These skills transfer directly to any monetary data analysis or KPI monitoring role.
"""